- package-lock.json
- package.json
A change based on my last "Add MUI as a dependency" PR review.
> Move mui/icons-material

- package.json
- tsconfig.json
> Excluded .stories.tsx files from generating type defs

- .storybook/main.ts
- package-lock.json
- package.json
- src/components/example/example.stories.tsx
- src/components/example/example.tsx
Closes #35 
Doesn't catch all accessibility issues but flags a substantial amount.  Most notably contrast issues for SVGs won't be flagged, as seen in the stories for the branding components.
> Add Storybook automated accessibility testing

- .storybook/preview.ts
- package-lock.json
- package.json
- src/components/Typography/index.ts
- src/index.ts
- src/theme/index.ts
- src/theme/typography.ts
1. Install two fonts (Roboto and Merriweather) through `npm install` and import them in `preview.ts` file and also put them in the peerDependency.
2. Design system tokens for typography goes under the typography field.
> Install fonts and define typeface constants

- .storybook/main.ts
- package-lock.json
- package.json
Closes #46 
Adds another tab that displays the whole code for the selected story.  If there are multiple stories in one `.stories.tsx` file it'll navigate to and highlight the currently selected story.
> Show code storybook addon

- README.md
- src/index.ts
> Add Usage to README and Theme Exports

- docs/components/mui/Checkbox.stories.tsx
- docs/components/mui/Divider.stories.tsx
- docs/components/mui/Select.stories.tsx
- docs/components/mui/Slider.stories.tsx
- docs/components/mui/Switch.stories.tsx
- docs/components/mui/Textfield.stories.tsx
These components are very complex, especially the TextField and Select. For now I've implemented straightforward interactive stories for them, but it doesn't cover all the possible use cases, some of which our design system may or may not make use of. Once the Design Team is finished with a design system for form components, I will return to these, and include specific stories that better document their intended usage within our design system. For now they can be a reference for how our Theme effects presentation MUI components.
> Material UI component stories for Select, Slider, Switch, TextField, and Checkbox

- .github/workflows/linter.yml
Corresponding ticket: Validate Linting passes on PRs
For now I just added PR linter, I'll return for this task later to add a github action for chromatic on PR!
I referenced this when I added PR linter: [https://github.com/marketplace/actions/super-linter](url)
> Add PR linter

- .github/workflows/chromatic.yml
- package-lock.json
- package.json
The Token has been added to the GitHub secrets.
> Chromatic integration

- .github/workflows/chromatic.yml
- .github/workflows/storybook.yml
Fixes #78 
I also updated the Chromatic workflow to use yarn, but more work needs to be done still to get Chromatic to work with the monorepo.
> Fix storybook GH pages workflow

- .github/workflows/chromatic.yml
- .github/workflows/storybook.yml
- docs/package.json
- package.json
- packages/ui-kit-components/package.json
- packages/ui-kit-components/src/index.ts
- packages/ui-kit-components/tsconfig.json
- packages/ui-kit-components/tsconfig.node.json
- packages/ui-kit-theme/package.json
- packages/ui-kit-theme/src/index.ts
- packages/ui-kit-theme/tsconfig.json
- packages/ui-kit-theme/tsconfig.node.json
- tsconfig.json
- yarn.lock
> Fix chromatic workflow for Monorepo & TS build error

- docs/src/design-system/brand/BrandDocPage.stories.tsx
- docs/src/design-system/brand/BrandDocPage.tsx
> Create brand doc page

- .changeset/itchy-mails-arrive.md
I created a changeset that simply bumps the patch version of Components, Theme, and Docs for the purpose of creating a small release to ensure the workflow behaves as expected. When this commit is merged, we should see a new release PR be created.
> First changeset created for testing a patch release

- packages/ui-kit-theme/src/overrides/MuiButton.ts
This change separate the button effects for the click and tab selection as the design on the figma.
https://user-images.githubusercontent.com/106985561/199970705-419b15db-590c-49fe-bb57-6c0f91dd30e7.mp4
> Focus with tab selections

- docs/src/Home.stories.mdx
> Add GitHub and NPM package links to Storybook

- docs/src/design-system/building-blocks/table/LongLabelExample.stories.tsx
- docs/src/design-system/building-blocks/table/LongLabelExample.tsx
- docs/src/design-system/building-blocks/table/TableExample.stories.tsx
- docs/src/design-system/building-blocks/table/TableExample.tsx
- docs/src/design-system/buttons/StatesPage.stories.tsx
- docs/src/design-system/tables/TableUsagePage.stories.tsx
- docs/src/design-system/tables/TableUsagePage.tsx
> Create table doc page

- docs/src/design-system/building-blocks/common/top-bar.tsx
- docs/src/design-system/buttons/DosDontsPage.tsx
1. Add responsive view for button dos&donts page.
2. Modify Topbar component based on the latest figma design.
Tablet View:
Large mobile View:
Small mobile View:
> Add responsive view for button dos&donts page

- docs/src/design-system/typography/TextStylesPage.tsx
- Fix the style bug of typography style page, since we override the Mui table theme.
- Small modification of the page based on the latest figma design.
> Fix typography style page style bug

- docs/src/mui/Divider.stories.tsx
> Fixed Divider story text issue

- README.md
- packages/ui-kit-components/README.md
- packages/ui-kit-theme/README.md
Closes #160 
Add shield links to npm packages and Storybook.
> Add Shields to READMEs

- .github/workflows/storybook.yml
> Fix issue 163: Storybook deployment heap memory limit reached

- docs/src/components/Graph.stories.tsx
- docs/src/components/Icons.stories.tsx
- docs/src/components/Pill.stories.tsx
- docs/src/components/TextSearch.stories.tsx
- docs/src/design-system/building-blocks/color/color-card-group.tsx
- docs/src/design-system/charts/generate-data.tsx
- docs/src/design-system/ticker-search/TickerSearchDesignPage.tsx
- docs/src/design-system/typography/TextStylesPage.tsx
- docs/src/mui/Chip.stories.tsx
- packages/ui-kit-components/src/components/Graph/graph.tsx
- packages/ui-kit-components/src/components/Pill/Pill.tsx
- packages/ui-kit-components/src/components/TextSearch/TextSearch.tsx
- packages/ui-kit-theme/src/overrides/MuiButton.ts
- packages/ui-kit-theme/src/overrides/MuiButtonBase.ts
- packages/ui-kit-theme/src/overrides/MuiChip.ts
- packages/ui-kit-theme/src/overrides/MuiDivider.ts
- packages/ui-kit-theme/src/overrides/MuiInputBase.ts
- packages/ui-kit-theme/src/overrides/MuiLinearProgress.ts
- packages/ui-kit-theme/src/overrides/MuiTableBody.ts
I'm stuck on 3 remaining warnings. I'm not sure how to resolve these types, so I've left them as is for now.
```
/Users/iandilling/Workspace/ui-kit-2022/packages/ui-kit-components/src/components/Graph/graph.tsx
246:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
/Users/iandilling/Workspace/ui-kit-2022/packages/ui-kit-theme/src/index.ts
18:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
25:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
✖ 3 problems (0 errors, 3 warnings)
```
> Corrected tslint warnings

- packages/ui-kit-components/src/components/Graph/graph.tsx
- packages/ui-kit-theme/src/index.ts
- packages/ui-kit-theme/src/overrides/MuiChip.ts
- packages/ui-kit-theme/src/overrides/MuiDivider.ts
- packages/ui-kit-theme/src/overrides/MuiLinearProgress.ts
> Fixed 3 remaining tslint warnings

- docs/.storybook/preview.tsx
- docs/src/components/SplashScreen.stories.tsx
- docs/src/components/SplashScreenStory.tsx
- docs/src/design-system/building-blocks/button/ButtonStatesExample.tsx
- packages/ui-kit-components/src/components/SplashScreen/SplashScreen.tsx
> Fix splash screen bug

- docs/src/Home.stories.mdx
> Move docs section to the top

- packages/ui-kit-components/src/components/TextSearch/TextSearch.tsx
- packages/ui-kit-theme/src/overrides/MuiAutocomplete.tsx
* Group Label color not matching dropdown background color
* Group Label covering IOS scrollbar.
> Fixed two TextSearch dropdown issues

- docs/src/playground/SearchPage.stories.tsx
- docs/src/playground/SearchPage.tsx
> Text input playground

- packages/ui-kit-components/src/components/PageNotFound/PageNotFound.tsx
The design team has decided to remove the top-left Logo on the 404 page.
> Removed top-left logo on 404 page

- docs/src/design-system/building-blocks/icons/with-text.tsx
> chore: replace the gap with more space in item

- packages/ui-kit-theme/src/overrides/MuiButtonBase.ts
> Base button outline radius

- docs/src/design-system/loader-spinner/LoaderSpinner.stories.tsx
- docs/src/design-system/loader-spinner/LoaderSpinner.tsx
> Loader doc

- .changeset/few-pants-check.md
Adding a new version bump changeset, logging some of the additions made over the last few weeks. I mainly need to trigger the release PR to check if Chromatic can generate a changeset from the PR.
> Added changesets for latest library additions

- .eslintignore
- packages/ui-kit-components/package.json
- packages/ui-kit-components/src/components/Button/__snapshots__/button.test.tsx.snap
- packages/ui-kit-components/src/components/Button/button.test.tsx
- packages/ui-kit-components/src/components/Button/button.tsx
Second part for test-button ticket providing more test cases
> chore: add more tests

- docs/src/design-system/building-blocks/color/color-card-group.tsx
- docs/src/design-system/building-blocks/icons/color.tsx
- docs/src/design-system/building-blocks/icons/icon-library.tsx
- docs/src/design-system/building-blocks/icons/purpose.tsx
- docs/src/design-system/building-blocks/icons/sizing.tsx
- docs/src/design-system/building-blocks/icons/with-text.tsx
- docs/src/design-system/color-palette/palette.tsx
- docs/src/design-system/icons/icons.tsx
- docs/src/design-system/typography/types-page.tsx
- packages/ui-kit-theme/src/breakpoints.ts
- packages/ui-kit-theme/src/index.ts
Updated the MUI breakpoints to be in line with Figma.  I also added an additional breakpoint `xxs: 0` for when you want to apply conditional code beneath 375px.
> Update MUI Breakpoints

- .changeset/blue-shirts-punch.md
- .changeset/thin-dancers-jump.md
- docs/src/components/Graph.stories.tsx
- docs/src/components/Typography.stories.tsx
- packages/ui-kit-components/src/components/Graph/graph.tsx
- packages/ui-kit-components/src/components/TextSearch/TextSearch.tsx
- packages/ui-kit-components/src/components/Typography/Typography.tsx
- packages/ui-kit-components/src/components/Typography/index.ts
- packages/ui-kit-components/src/index.ts
Next I will add these loading states into the Stock Page playground.
> Loading states for TextSearch, Graph, and Typography

- docs/src/playground/ExamplePage.tsx
- docs/src/playground/StocksPage.stories.tsx
- docs/src/playground/components/KeyStatistics.tsx
- docs/src/playground/components/Sidebar.tsx
Forgot to mention this in standup. This adds a loading state to the Stock Page playground story.
> Loading states added to the Stock Page playground

- packages/ui-kit-components/src/components/Graph/graph-utils.ts
- packages/ui-kit-components/src/components/Graph/graph.test.tsx
- packages/ui-kit-components/src/components/Graph/graph.tsx
I managed to mock the register plugins call to avoid that error. The other issue I was having was due to a mistake I was making with the Jest blocks.
> Unit tests for Graph component and graph utility functions
