AdaptiveConsulting/ui-kit-2022

.github/workflows/storybook.yml
.storybook/main.cjs
package.json

This should deploy Storybook to Github Pages once Pages is enabled for this project. The projects pages Source should be set to "GitHub Actions".
I got it running in a test github repo:
https://github.com/iandilling-adaptive/test-project
https://iandilling-adaptive.github.io/test-project

Storybook GH Pages CD workflow

---

package.json
src/theme/index.ts
src/theme/palette.ts

For now I've simply included a file that contains the color hex codes.
TODO: I've started integrating them into two MUI compatible themes: a light and a dark theme. I need to figure out how to map the design system colors to MUI's theme palette properties for each theme type (light and dark), particularly the Core-Primary and Core-Secondary colors. MUI has three properties for the "primary" and "secondary" palette colors: "light", "dark", and "main". The "light" and "dark" here are not the same as the theme mode (light mode or dark mode), they are a light and dark variant of the "main" color. So there will have to be a set of "light, "dark", and "main" for each theme color type (primary, secondary, error, etc.) for each theme (light/dark). Some colors might be in both themes, under a …

Initialized palettes and themes for light and dark modes

---

.eslintrc.json
package-lock.json
package.json

Closes #52 
Unused imports will now be flagged by eslint as an error.  Running `npm run lint:fix` will remove unused imports from files in the repo.

Flag unused imports as errors & removing them

---

.github/workflows/publish-npm.yml
.github/workflows/storybook.yml
.gitignore

Before this is merged, the NPM_TOKEN needs to be added to Github's managed secrets for this project.
Closes #36

GH action workflow for NPM publish on release

---

docs/src/components/Pill.stories.tsx
docs/src/components/mui/Button.stories.tsx
docs/src/components/mui/Chip.stories.tsx
packages/ui-kit-components/src/components/Pill/Pill.tsx
packages/ui-kit-components/src/components/Pill/index.ts
packages/ui-kit-components/src/index.ts
packages/ui-kit-theme/src/overrides/MuiButtonBase.ts
packages/ui-kit-theme/src/overrides/MuiChip.ts
packages/ui-kit-theme/src/overrides/index.ts

There's so much overlap between the Pills and Button components, that these theme overrides can likely be shared between the two. The Button could be refactored to set the overrides, and then the MUI Button can be used for many of the Button and Pills use cases.

Theme overrides for the MUI Chip for Pills and Badges components

---

.github/workflows/chromatic.yml

This is a fix to set the proper working directory for the Chromatic build.

Set correct chromatic workflow directory

---

packages/ui-kit-theme/src/overrides/MuiButton.ts

before the padding is 2px on the left and right:
currently the padding has been changed to 4px:

fix: change the left and right padding of button to 4px

---

docs/.storybook/preview.tsx
docs/src/design-system/building-blocks/common/top-bar.tsx
docs/src/design-system/building-blocks/typography/font-example.tsx
docs/src/design-system/building-blocks/typography/font-examples.tsx
docs/src/design-system/building-blocks/typography/text-sample.tsx
docs/src/design-system/building-blocks/typography/type-card.tsx
docs/src/design-system/typography/TextStylesPage.tsx
docs/src/design-system/typography/types-page.tsx

Based on my test, we have already set  different background colors and text colors for light and dark modes. So when we create the documentation pages for our components, we don't need to have fixed background color and text color, then we should have basic pages for both dark mode and light mode for users to switch.
Besides, since there are no designs for 'light' mode pages, I think we can adjust some special colors on the documentation in light mode to make the whole page look more coordinated.
Here are my tests for Typography styles and types pages.

Add light mode for Typography styles and types pages

---

docs/src/components/SplashScreen.stories.tsx
docs/src/mui/Divider.stories.tsx

The vertical Divider is now set to extend the length of the viewport. I also fixed the height of the Splash Screen when in doc mode.

Fixed Storybook vertical divider height and splash screen height in doc view

---

.changeset/config.json
.github/workflows/publish-components.yml
.github/workflows/publish-theme.yml
.github/workflows/release.yml
DEVELOP.md
README.md
package.json

Closes #74 
This includes release automation and changelog generation with Changesets, but it does not employ the branching strategy I shared. To automate that strategy with Changesets will require additional configuration, since Changesets will generate, not a single release, but a release for every package. This means that each package can have a different released version, which makes determining when to create a permanent release branch much more opaque.

Changeset config and GH CI setup

---

.github/workflows/release.yml
package.json
yarn.lock

Modified `release.yml` to ensure that `yarn.lock` is updated when generating a workflow PR. Otherwise all our Actions will break after merging a release PR. This commit also updates `yarn.lock` to be compatible with the new version bump I merged earlier. The workflow should now rerun and succeed this time.

Fixed issue with yarn.lock not updating in the changeset version workflow

---

README.md
package.json
yarn.lock

This should make it easier to start developing the packages with storybook open. 
I also discovered two issues that exist both in our present development workflow and this new concurrent script workflow:
https://github.com/AdaptiveConsulting/ui-kit-2022/issues/127
https://github.com/AdaptiveConsulting/ui-kit-2022/issues/128

Added a single dev script for running all dev watchers concurrently

---

docs/.storybook/main.ts

Removing the V7 features seems to fix both of these issues. I added these before we moved to a monorepo to fix an issue with Storybooks manager having issues importing our other TS files into storybook's TS config files, but now that we import from the JS build files, it should be safe to remove them.
Fixes #128
Fixes #127

Removed storyStoreV7 and babelModeV7

---

.eslintignore

The linter is trying to lint js build artifacts in the storybook-static directory. This prevents it from doing so.

Added storybook-static to .eslintignore

---

docs/src/design-system/building-blocks/icons/color.tsx
docs/src/design-system/building-blocks/icons/icon-library.tsx
docs/src/design-system/building-blocks/icons/icons.constants.ts
docs/src/design-system/building-blocks/icons/purpose.tsx
docs/src/design-system/building-blocks/icons/sizing.tsx
docs/src/design-system/building-blocks/icons/with-text.tsx
docs/src/design-system/icons/icons.tsx

Closes #162 
Added a responsive design for the icon docs page.  Smallest screen size it supports is 320px.

Icon Docs Responsive Design

---

.github/workflows/chromatic.yml

Same fix as the one in the Storybook workflow but for the Chromatic workflow.

Fixed chromatic deploy heap memory out of bounds error

---

docs/.storybook/preview.tsx
docs/src/Home.stories.mdx

Fixes #114
There is still an issue of incorrect pseudo state rendering when switching between stories in docs mode, but the original issue is solved. I'll create another issue for this.

Fixed issue 114: Pseudo states don't render when toggling theme

---

docs/src/design-system/brand/BrandDocPage.tsx

Closes #167 
Added responsive styling to the branding doc on Storybook.  Supports 320px as the smallest size.

Branding Doc Responsive Styling

---

docs/.storybook/preview.tsx
docs/src/playground/ExamplePage.tsx
docs/src/playground/StocksPage.stories.tsx

I removed the navbar I mentioned in standup since I need to clarify with Nate on how its branding should present on smaller screens.  
The playground page doesn't have it's own `"Category"` for now.  I thought it'd be better to have a simple grouping since there's not much content.  It displays first before the categories.

Add Playground Page

---

docs/src/design-system/building-blocks/table/IndexTickerMobile.tsx
docs/src/design-system/building-blocks/table/TickerBarMobile.tsx
docs/src/design-system/tables/FooterIndexTicker.stories.tsx
docs/src/design-system/tables/FooterIndexTicker.tsx
docs/src/design-system/tables/TableUsagePage.stories.tsx

I was not able to display the mobile style of` IndexTickers` componenet directly on this doc page(since this component was made responsive based on the screen size), so I had some extra code of `IndexTickerMobile` and `TickerBarMobile` in the `building block ` to just be used in this page. (Example doc page: [https://www.figma.com/file/vVwPje7l17NXssVR86wfYn/Reactive-Analytics---Design-System?node-id=3030%3A43447&t=rBza3PJrYEqW5BgJ-0](url))

Create footer index ticker doc page

---

docs/src/design-system/charts/mobile-responsiveness.tsx

To solve the labels overlap issue on the graph doc, we show only certain charts with sizes accordingly to the screen. 
like for mobile:
for tablet:
And for normal screen:

Graph doc overlap

---

docs/src/design-system/tables/FooterIndexTicker.tsx
packages/ui-kit-components/src/components/IndexTickers/IndexTickers.tsx

As discussed with Nate, when we reach the breakpoints `md` (the screen size is smaller than 900px), these two examples will be removed from the doc page.

Add responsive view for index ticker doc page

---

docs/src/design-system/pills/pills-badges-usage.tsx

Closes #209 
Updated to have the text be on top of the pills and badges for mobile view.  This also fixed the overlap issue.
New appearance (320px):

Mobile Friendly Pills & Badges Story

---

docs/src/playground/ExamplePage.tsx
docs/src/playground/components/StockPriceFooter.tsx

Currently, I just created `StockerPriceFooter` in the playground component,  later based on the overall responsive layout and the Figma design, it will be modified to fit the whole page.

Create playground stock price footer

---

packages/ui-kit-theme/src/overrides/MuiTable.ts

It seems that the chrome border issue was caused by `border-collapse` property. After the value was changed from `Collapse `to `Separate`, the issue was gone.

Fix chrome border issue

---

docs/src/design-system/building-blocks/button/ButtonStatesExample.stories.tsx
docs/src/design-system/building-blocks/button/ButtonStatesExample.tsx
docs/src/design-system/buttons/StatesPage.stories.tsx
packages/ui-kit-theme/src/overrides/MuiButton.ts

Closes #218 
Added backwards compatibility for the focus border.  It should now no longer disappear on certain older devices / browsers.

Button Focus Border

---

package.json

I needed to explicitly tell yarn to update the lockfile to ignore it's immutability check. I'm not sure why this didn't cause a failure the last time this script ran, but this should ensure it behaves as expected.

Fixed error in Release GH workflow
